server:
  port: 8091

security:
  basic:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health, shutdown, prometheus

springfox:
  title: 'FINT SSE Adapter Felles Kodeverk'
  version: '@version@'

base-url: https://beta.felleskomponent.no/felles/kodeverk/provider
fint:
  adapter:
    organizations: fint.felles.kodeverk
    sse-endpoint: ${base-url}/sse/%s
    status-endpoint: ${base-url}/status
    response-endpoint: ${base-url}/response

  ssb-klass:
    root-url: http://data.ssb.no/api/klass/v1/classifications
    kommune: 131
    fylke: 104

